-- One row per player per pro match: the performance grain.
select
    pm.match_id,
    pm.player_slot,
    pm.is_radiant,
    case when pm.is_radiant then m.radiant_team_id else m.dire_team_id end as team_id,
    case when pm.is_radiant then m.radiant_team_name else m.dire_team_name end as team_name,
    pm.account_id,
    pm.player_name,
    pm.hero_id,
    h.hero_name,
    pm.is_win,
    pm.kills,
    pm.deaths,
    pm.assists,
    pm.kda,
    pm.last_hits,
    pm.denies,
    pm.gold_per_min,
    pm.xp_per_min,
    pm.level,
    pm.net_worth,
    pm.hero_damage,
    pm.tower_damage,
    pm.hero_healing,
    pm.obs_placed,
    pm.sen_placed,
    pm.camps_stacked,
    pm.rune_pickups,
    pm.roshans_killed,
    pm.towers_killed,
    pm.teamfight_participation,
    pm.stuns,
    pm.aghanims_scepter = 1 as has_aghanims_scepter,
    pm.aghanims_shard = 1 as has_aghanims_shard,
    pm.leaver_status,
    pm.abandons,
    m.started_at,
    m.match_date,
    m.patch_id,
    m.patch_name,
    m.league_id,
    m.league_name,
    m.duration_min
from {{ ref('stg_match_players') }} as pm
inner join {{ ref('fact_match') }} as m on m.match_id = pm.match_id
left join {{ ref('stg_heroes') }} as h on h.hero_id = pm.hero_id
