-- Ten rows per match. The parent match id rides dlt's _dlt_parent_id; we resolve it
-- back to match_id here so every downstream join is on the natural key.
select
    m.match_id,
    p.player_slot,
    p.is_radiant,
    p.account_id,
    p.personaname as player_name,
    p.hero_id,
    p.hero_variant,
    p.kills,
    p.deaths,
    p.assists,
    p.last_hits,
    p.denies,
    p.gold_per_min,
    p.xp_per_min,
    p.level,
    p.net_worth,
    p.hero_damage,
    p.tower_damage,
    p.hero_healing,
    p.obs_placed,
    p.sen_placed,
    p.camps_stacked,
    p.rune_pickups,
    p.roshans_killed,
    p.towers_killed,
    p.teamfight_participation,
    p.stuns,
    p.item_0,
    p.item_1,
    p.item_2,
    p.item_3,
    p.item_4,
    p.item_5,
    p.item_neutral,
    p.aghanims_scepter,
    p.aghanims_shard,
    p.lane,
    p.lane_role,
    p.is_roaming,
    p.leaver_status,
    p.abandons,
    p.kda,
    p.win = 1 as is_win
from {{ source('raw', 'match_details__players') }} as p
inner join {{ source('raw', 'match_details') }} as m on m._dlt_id = p._dlt_parent_id
